// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using NMAC.Core;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
#nullable disable

namespace NMAC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308185911_AddOrphanedSubscriptions")]
    partial class AddOrphanedSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NMAC.ContentDistribution", b =>
                {
                    b.Property<string>("TopicUri")
                        .HasColumnType("text")
                        .HasColumnName("topic_uri");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("TopicUri")
                        .HasName("pk_content_distributions");

                    b.ToTable("content_distributions", (string)null);
                });

            modelBuilder.Entity("NMAC.OrphanedSubscription", b =>
                {
                    b.Property<string>("CallbackUri")
                        .HasColumnType("text")
                        .HasColumnName("callback_uri");

                    b.Property<DateTimeOffset?>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration");

                    b.Property<string>("Secret")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret");

                    b.Property<Guid?>("Slug")
                        .HasColumnType("uuid")
                        .HasColumnName("slug");

                    b.Property<string>("TopicUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic_uri");

                    b.HasKey("CallbackUri")
                        .HasName("pk_orphaned_subscriptions");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_orphaned_subscriptions_slug");

                    b.ToTable("orphaned_subscriptions", (string)null);
                });

            modelBuilder.Entity("NMAC.Subscription", b =>
                {
                    b.Property<string>("TopicUri")
                        .HasColumnType("text")
                        .HasColumnName("topic_uri");

                    b.Property<string>("CallbackUri")
                        .HasColumnType("text")
                        .HasColumnName("callback_uri");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("Expiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration");

                    b.Property<string>("Mode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("mode");

                    b.Property<string>("Secret")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret");

                    b.Property<Guid?>("Slug")
                        .HasColumnType("uuid")
                        .HasColumnName("slug");

                    b.HasKey("TopicUri")
                        .HasName("pk_subscriptions");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_slug");

                    b.HasIndex("Enabled", "CallbackUri", "Expiration")
                        .HasDatabaseName("ix_subscriptions_enabled_callback_uri_expiration");

                    b.ToTable("subscriptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
